### ISSUE TITLE
请教一下这个记录消息存储这个功能是如何实现的呀

### ISSUE THREAD

**Issue by AnCool-OvO** [labi-xiaoxin/wechat-bot-wechat4u#1]

**Comment by labi-xiaoxin** [comment]
可以自行提取消息进行存储：`/src/core/sendMessage.js`
目前我是将其做在后端，通过后端控制消息存储

**Comment by AnCool-OvO** [comment]
> 可以自行提取消息进行存储：`/src/core/sendMessage.js` 目前我已经在仓库做了，通过数据控制消息存储

 请问这个有没有类似的教学呀想学习一下

**Comment by labi-xiaoxin** [comment]
暂时没有，后端考虑将数据存入数据库、或是缓存，这个看你设计了

**Comment by AnCool-OvO** [comment]
> 暂时没有，暂时考虑将数据存入数据库、或者存储，这个看你设计了


好的感谢回复
